--------------------------------------------------------
--  File created - Th? b?y-tháng sáu-25-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence MADT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##USERADMIN"."MADT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MADV_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##USERADMIN"."MADV_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MAHD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##USERADMIN"."MAHD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MAKH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##USERADMIN"."MAKH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MAKM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##USERADMIN"."MAKM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MALSP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##USERADMIN"."MALSP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MANV_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##USERADMIN"."MANV_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MAPDV_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##USERADMIN"."MAPDV_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MAPN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##USERADMIN"."MAPN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MASP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##USERADMIN"."MASP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CTDV
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."CTDV" 
   (	"MAPDV" NUMBER, 
	"MADV" NUMBER, 
	"SLDV" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CTHD
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."CTHD" 
   (	"MAHD" NUMBER, 
	"MASP" NUMBER, 
	"SLSP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CTNSP
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."CTNSP" 
   (	"MAPN" NUMBER, 
	"MASP" NUMBER, 
	"MADT" NUMBER, 
	"SLNHAP" NUMBER, 
	"DONGIANHAP" NUMBER, 
	"THANHTIEN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DICHVU
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."DICHVU" 
   (	"MADV" NUMBER(5,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TENDV" VARCHAR2(40 BYTE), 
	"TIENDV" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOITAC
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."DOITAC" 
   (	"MADT" NUMBER(5,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TENCTY" VARCHAR2(100 BYTE), 
	"DIACHI" VARCHAR2(100 BYTE), 
	"SDT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOADON
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."HOADON" 
   (	"MAHD" NUMBER(5,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MAKH" NUMBER, 
	"MANV" NUMBER, 
	"MAKM" NUMBER, 
	"NGAYTAOHD" DATE, 
	"TONGTIEN" NUMBER, 
	"TIENKM" NUMBER, 
	"THANHTIEN" NUMBER, 
	"GHICHU" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KHACHHANG
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."KHACHHANG" 
   (	"MAKH" NUMBER(5,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TENKH" VARCHAR2(40 BYTE), 
	"GIOITINH" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"SDT" NUMBER, 
	"DIEM" NUMBER, 
	"LOAI" VARCHAR2(20 BYTE), 
	"NGAYSINH" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KHUYENMAI
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."KHUYENMAI" 
   (	"MAKM" NUMBER(5,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LOAIKM" VARCHAR2(40 BYTE), 
	"TYLEGIAM" NUMBER, 
	"TIENGIAM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOAISANPHAM
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."LOAISANPHAM" 
   (	"MALSP" NUMBER(5,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TENLSP" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NHANVIEN
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."NHANVIEN" 
   (	"MANV" NUMBER(5,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TENNV" VARCHAR2(40 BYTE), 
	"CHUCVU" VARCHAR2(40 BYTE), 
	"GIOITINH" VARCHAR2(20 BYTE), 
	"NGAYSINH" DATE, 
	"DIACHI" VARCHAR2(40 BYTE), 
	"SDT" NUMBER, 
	"NGAYVAOLAM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHIEUDV
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."PHIEUDV" 
   (	"MAPDV" NUMBER(5,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MANV" NUMBER, 
	"MAKH" NUMBER, 
	"NGAYTAOPDV" DATE, 
	"TONGSLDV" NUMBER, 
	"TONGTIEN" NUMBER, 
	"TRATRUOC" NUMBER, 
	"THANHTIEN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHIEUNHAP
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."PHIEUNHAP" 
   (	"MAPN" NUMBER(5,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MANV" NUMBER, 
	"NGAYTAOPN" DATE, 
	"TONGSLSP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SANPHAM
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."SANPHAM" 
   (	"MASP" NUMBER(5,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MALSP" NUMBER, 
	"TENSP" VARCHAR2(40 BYTE), 
	"SLTON" NUMBER, 
	"DVT" VARCHAR2(10 BYTE), 
	"DONGIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAIKHOAN
--------------------------------------------------------

  CREATE TABLE "C##USERADMIN"."TAIKHOAN" 
   (	"MANV" NUMBER(5,0), 
	"TENTK" VARCHAR2(40 BYTE), 
	"MATKHAU" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##USERADMIN.CTDV
SET DEFINE OFF;
Insert into C##USERADMIN.CTDV (MAPDV,MADV,SLDV) values ('1','1','2');
Insert into C##USERADMIN.CTDV (MAPDV,MADV,SLDV) values ('2','2','6');
Insert into C##USERADMIN.CTDV (MAPDV,MADV,SLDV) values ('3','3','3');
Insert into C##USERADMIN.CTDV (MAPDV,MADV,SLDV) values ('4','4','4');
Insert into C##USERADMIN.CTDV (MAPDV,MADV,SLDV) values ('5','5','2');
REM INSERTING into C##USERADMIN.CTHD
SET DEFINE OFF;
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('7','7','1');
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('7','1','1');
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('1','1','3');
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('2','2','11');
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('3','3','5');
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('4','4','6');
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('5','5','8');
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('7','5','1');
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('7','4','1');
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('7','9','1');
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('11','4','2');
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('9','3','1');
Insert into C##USERADMIN.CTHD (MAHD,MASP,SLSP) values ('10','4','1');
REM INSERTING into C##USERADMIN.CTNSP
SET DEFINE OFF;
Insert into C##USERADMIN.CTNSP (MAPN,MASP,MADT,SLNHAP,DONGIANHAP,THANHTIEN) values ('6','1','3','39','51613','2012907');
Insert into C##USERADMIN.CTNSP (MAPN,MASP,MADT,SLNHAP,DONGIANHAP,THANHTIEN) values ('1','1','1','10','2700000','0');
Insert into C##USERADMIN.CTNSP (MAPN,MASP,MADT,SLNHAP,DONGIANHAP,THANHTIEN) values ('2','2','2','5','30000000','0');
Insert into C##USERADMIN.CTNSP (MAPN,MASP,MADT,SLNHAP,DONGIANHAP,THANHTIEN) values ('3','3','3','3','3500000','0');
Insert into C##USERADMIN.CTNSP (MAPN,MASP,MADT,SLNHAP,DONGIANHAP,THANHTIEN) values ('4','4','4','15','2000000','0');
Insert into C##USERADMIN.CTNSP (MAPN,MASP,MADT,SLNHAP,DONGIANHAP,THANHTIEN) values ('5','5','5','8','4000000','0');
Insert into C##USERADMIN.CTNSP (MAPN,MASP,MADT,SLNHAP,DONGIANHAP,THANHTIEN) values ('6','8','3','13','32258','419354');
Insert into C##USERADMIN.CTNSP (MAPN,MASP,MADT,SLNHAP,DONGIANHAP,THANHTIEN) values ('6','4','3','26','32258','838708');
Insert into C##USERADMIN.CTNSP (MAPN,MASP,MADT,SLNHAP,DONGIANHAP,THANHTIEN) values ('7','7','1','32','64516','2064512');
REM INSERTING into C##USERADMIN.DICHVU
SET DEFINE OFF;
Insert into C##USERADMIN.DICHVU (MADV,TENDV,TIENDV) values ('1','MUA VÀNG','5600000');
Insert into C##USERADMIN.DICHVU (MADV,TENDV,TIENDV) values ('2','BÁN VÀNG','5650000');
Insert into C##USERADMIN.DICHVU (MADV,TENDV,TIENDV) values ('3','S?A SIZE NH?N','100000');
Insert into C##USERADMIN.DICHVU (MADV,TENDV,TIENDV) values ('4','HÀN DÂY CHUY?N','250000');
Insert into C##USERADMIN.DICHVU (MADV,TENDV,TIENDV) values ('5','ÐÁNH BÓNG VANG','300000');
REM INSERTING into C##USERADMIN.DOITAC
SET DEFINE OFF;
Insert into C##USERADMIN.DOITAC (MADT,TENCTY,DIACHI,SDT) values ('1','T?p ðoàn DOJI','T?a nhà DOJI Tower, 5 Lê Du?n, Q. Ba Ð?nh, Hà N?i','18001168');
Insert into C##USERADMIN.DOITAC (MADT,TENCTY,DIACHI,SDT) values ('2','Công ty c? ph?n Vàng b?c ðá qu? Phú Nhu?n (PNJ)','170E Phan Ðãng Lýu, P. 3, Q. Phú Nhu?n, TP. HCM','1800545457');
Insert into C##USERADMIN.DOITAC (MADT,TENCTY,DIACHI,SDT) values ('3','Công ty TNHH MTV Vàng b?c ðá qu? Sài G?n (SJC)','418 - 420 Nguy?n Th? Minh Khai, P. 5, Q. 3, TP. HCM','2839293388');
Insert into C##USERADMIN.DOITAC (MADT,TENCTY,DIACHI,SDT) values ('4','Công ty Vàng b?c ðá qu? Sacombank (SBJ)','278 Nam KyÌ KhõÒi NghiÞa, PhýõÌng 8, Quâòn 3, TP. HCM','909543466');
Insert into C##USERADMIN.DOITAC (MADT,TENCTY,DIACHI,SDT) values ('5','Công ty Vàng b?c Ðá qu? B?o Tín Minh Châu','29 Tr?n Nhân Tông, Hai Bà Trýng, Hà N?i','1800585899');
Insert into C##USERADMIN.DOITAC (MADT,TENCTY,DIACHI,SDT) values ('6','Công ty TNHH Vàng b?c ðá qu? H? Long ( HJC)','8 Hàng B?c, Hoàn Ki?m, Hà N?i','911519466');
Insert into C##USERADMIN.DOITAC (MADT,TENCTY,DIACHI,SDT) values ('7','T?p ðoàn Vàng b?c ðá qu? Phú Qu?','30 Tr?n Nhân Tông, Q. Hai Bà Trýng, Hà N?i','906263030');
Insert into C##USERADMIN.DOITAC (MADT,TENCTY,DIACHI,SDT) values ('8','Công ty C? ph?n Th? Gi?i Kim Cýõng','59 Ðý?ng 27, Phý?ng 6, Q. G? V?p, TP. HCM','1800779999');
Insert into C##USERADMIN.DOITAC (MADT,TENCTY,DIACHI,SDT) values ('9','Thýõng hi?u Ngoc Tham Jewelry ( NTJ)','25/2 Nguy?n Hu?nh Ð?c, P.8, Tp.M? Tho, Ti?n Giang','1800599973');
Insert into C##USERADMIN.DOITAC (MADT,TENCTY,DIACHI,SDT) values ('10','Thýõng hi?u V?nh Cara - Diamond Jewelry','406 V? Vãn T?n, P.5, Q.3, Tp.HCM','2838181111');
Insert into C##USERADMIN.DOITAC (MADT,TENCTY,DIACHI,SDT) values ('11','Thýõng hi?u C?u Long Jewelry','70-72 Lê Thánh Tôn, Qu?n 1, TP. H? Chí Minh, Vi?t Nam','932106439');
Insert into C##USERADMIN.DOITAC (MADT,TENCTY,DIACHI,SDT) values ('12','Thýõng hi?u Ðá Qúy','12/6 Lê L?i, Qu?n 5, TP. H? Chí Minh, Vi?t Nam','954266439');
REM INSERTING into C##USERADMIN.HOADON
SET DEFINE OFF;
Insert into C##USERADMIN.HOADON (MAHD,MAKH,MANV,MAKM,NGAYTAOHD,TONGTIEN,TIENKM,THANHTIEN,GHICHU) values ('7','11','1','1',to_date('25-06-2022','DD-MM-RRRR'),'21090000','2109000','18981000',null);
Insert into C##USERADMIN.HOADON (MAHD,MAKH,MANV,MAKM,NGAYTAOHD,TONGTIEN,TIENKM,THANHTIEN,GHICHU) values ('9','11','1',null,to_date('25-06-2022','DD-MM-RRRR'),'3000000','0','3000000',null);
Insert into C##USERADMIN.HOADON (MAHD,MAKH,MANV,MAKM,NGAYTAOHD,TONGTIEN,TIENKM,THANHTIEN,GHICHU) values ('1','1','1','2',to_date('01-05-2020','DD-MM-RRRR'),'15800000','500000','15300000','NO');
Insert into C##USERADMIN.HOADON (MAHD,MAKH,MANV,MAKM,NGAYTAOHD,TONGTIEN,TIENKM,THANHTIEN,GHICHU) values ('2','2','3','2',to_date('01-05-2020','DD-MM-RRRR'),'10200000','200000','10000000','NO');
Insert into C##USERADMIN.HOADON (MAHD,MAKH,MANV,MAKM,NGAYTAOHD,TONGTIEN,TIENKM,THANHTIEN,GHICHU) values ('3','2','1','2',to_date('01-05-2020','DD-MM-RRRR'),'18000000','500000','17500000','NO');
Insert into C##USERADMIN.HOADON (MAHD,MAKH,MANV,MAKM,NGAYTAOHD,TONGTIEN,TIENKM,THANHTIEN,GHICHU) values ('4','4','3','5',to_date('23-05-2020','DD-MM-RRRR'),'20000000','500000','19500000','NO');
Insert into C##USERADMIN.HOADON (MAHD,MAKH,MANV,MAKM,NGAYTAOHD,TONGTIEN,TIENKM,THANHTIEN,GHICHU) values ('5','5','1','6',to_date('30-05-2020','DD-MM-RRRR'),'8000000','200000','7800000','NO');
Insert into C##USERADMIN.HOADON (MAHD,MAKH,MANV,MAKM,NGAYTAOHD,TONGTIEN,TIENKM,THANHTIEN,GHICHU) values ('10','11','1',null,to_date('25-06-2022','DD-MM-RRRR'),'5000000','0','5000000',null);
Insert into C##USERADMIN.HOADON (MAHD,MAKH,MANV,MAKM,NGAYTAOHD,TONGTIEN,TIENKM,THANHTIEN,GHICHU) values ('11','11','1',null,to_date('25-06-2022','DD-MM-RRRR'),'10000000','0','10000000',null);
REM INSERTING into C##USERADMIN.KHACHHANG
SET DEFINE OFF;
Insert into C##USERADMIN.KHACHHANG (MAKH,TENKH,GIOITINH,EMAIL,SDT,DIEM,LOAI,NGAYSINH) values ('11','V? THÀNH ÐÔ','NAM','vothanhdo20013@gmail.com','938597366','18000000','Thân Thi?t',to_date('11-06-1987','DD-MM-RRRR'));
Insert into C##USERADMIN.KHACHHANG (MAKH,TENKH,GIOITINH,EMAIL,SDT,DIEM,LOAI,NGAYSINH) values ('1','TR?N NG?C TU?N ANH','NAM','TRANNGOCTUANANH@GMAIL.COM','768470225','0','VIP',to_date('10-02-1985','DD-MM-RRRR'));
Insert into C##USERADMIN.KHACHHANG (MAKH,TENKH,GIOITINH,EMAIL,SDT,DIEM,LOAI,NGAYSINH) values ('2','TR?N KIM ANH','N?','TRANKIMANH@GMAIL.COM','369837518','0','VIP',to_date('03-08-1980','DD-MM-RRRR'));
Insert into C##USERADMIN.KHACHHANG (MAKH,TENKH,GIOITINH,EMAIL,SDT,DIEM,LOAI,NGAYSINH) values ('3','V? DUY H?I','NAM','VUDUYHAI@GMAIL.COM','938597366','0','VIP',to_date('11-06-1987','DD-MM-RRRR'));
Insert into C##USERADMIN.KHACHHANG (MAKH,TENKH,GIOITINH,EMAIL,SDT,DIEM,LOAI,NGAYSINH) values ('4','HÁN TH? KIM DUYÊN ','N?','HANTHIKIMDUYEN@GMAIL.COM','975973356','0','VIP',to_date('16-05-1995','DD-MM-RRRR'));
Insert into C##USERADMIN.KHACHHANG (MAKH,TENKH,GIOITINH,EMAIL,SDT,DIEM,LOAI,NGAYSINH) values ('5','TR?N KIM NG?C','N?','TRANKIMNGOC@GMAIL.COM','709374592','0','M?i',to_date('30-05-1995','DD-MM-RRRR'));
Insert into C##USERADMIN.KHACHHANG (MAKH,TENKH,GIOITINH,EMAIL,SDT,DIEM,LOAI,NGAYSINH) values ('6','PH?M TH? NG?C NHÝ','N?','PHAMTHINGOCNHU@GMAIL.COM','747397367','0','VIP',to_date('14-10-1998','DD-MM-RRRR'));
Insert into C##USERADMIN.KHACHHANG (MAKH,TENKH,GIOITINH,EMAIL,SDT,DIEM,LOAI,NGAYSINH) values ('7','NGUY?N HOÀNG TÚ','N?','NGUYENHOANGTU@GMAIL.COM','947962356','0','VIP',to_date('12-04-1979','DD-MM-RRRR'));
Insert into C##USERADMIN.KHACHHANG (MAKH,TENKH,GIOITINH,EMAIL,SDT,DIEM,LOAI,NGAYSINH) values ('8','HU?NH THU TUY?T','N?','HUYNHTHUTUYET@GMAIL.COM','915743268','0','M?i',to_date('17-07-1974','DD-MM-RRRR'));
Insert into C##USERADMIN.KHACHHANG (MAKH,TENKH,GIOITINH,EMAIL,SDT,DIEM,LOAI,NGAYSINH) values ('9','HOÀNG MINH TU?N','NAM','HOANGMINHTUAN@GMAIL.COM','938571923','0','M?i',to_date('08-01-2000','DD-MM-RRRR'));
Insert into C##USERADMIN.KHACHHANG (MAKH,TENKH,GIOITINH,EMAIL,SDT,DIEM,LOAI,NGAYSINH) values ('10','ÐOÀN T?N TRUNG','NAM','DOANTANTRUNG@GMAIL.COM','369485285','0','VIP',to_date('20-10-1984','DD-MM-RRRR'));
REM INSERTING into C##USERADMIN.KHUYENMAI
SET DEFINE OFF;
Insert into C##USERADMIN.KHUYENMAI (MAKM,LOAIKM,TYLEGIAM,TIENGIAM) values ('1','KM TRONG NGÀY','10','0');
Insert into C##USERADMIN.KHUYENMAI (MAKM,LOAIKM,TYLEGIAM,TIENGIAM) values ('2','KM S?N PH?M','20','100000');
Insert into C##USERADMIN.KHUYENMAI (MAKM,LOAIKM,TYLEGIAM,TIENGIAM) values ('3','KM SINH NH?T','30','500000');
Insert into C##USERADMIN.KHUYENMAI (MAKM,LOAIKM,TYLEGIAM,TIENGIAM) values ('4','KM MÙA D?CH','20','300000');
Insert into C##USERADMIN.KHUYENMAI (MAKM,LOAIKM,TYLEGIAM,TIENGIAM) values ('5','KM NGÀY QU?C T? PH? N?','30','500000');
Insert into C##USERADMIN.KHUYENMAI (MAKM,LOAIKM,TYLEGIAM,TIENGIAM) values ('6','KM NGÀY PH? N? VN','30','500000');
Insert into C##USERADMIN.KHUYENMAI (MAKM,LOAIKM,TYLEGIAM,TIENGIAM) values ('7','KM BLACK FRIDAY','30','1000000');
REM INSERTING into C##USERADMIN.LOAISANPHAM
SET DEFINE OFF;
Insert into C##USERADMIN.LOAISANPHAM (MALSP,TENLSP) values ('1','NH?N');
Insert into C##USERADMIN.LOAISANPHAM (MALSP,TENLSP) values ('2','DÂY CHUY?N');
Insert into C##USERADMIN.LOAISANPHAM (MALSP,TENLSP) values ('3','L?C TAY');
Insert into C##USERADMIN.LOAISANPHAM (MALSP,TENLSP) values ('4','BÔNG TAI');
Insert into C##USERADMIN.LOAISANPHAM (MALSP,TENLSP) values ('5','V?NG C?');
REM INSERTING into C##USERADMIN.NHANVIEN
SET DEFINE OFF;
Insert into C##USERADMIN.NHANVIEN (MANV,TENNV,CHUCVU,GIOITINH,NGAYSINH,DIACHI,SDT,NGAYVAOLAM) values ('1','NGUY?N TRÝ?NG PHÝÕNG LOAN','QL','N?',to_date('01-05-1995','DD-MM-RRRR'),'TPHCM','769482996',to_date('07-01-2020','DD-MM-RRRR'));
Insert into C##USERADMIN.NHANVIEN (MANV,TENNV,CHUCVU,GIOITINH,NGAYSINH,DIACHI,SDT,NGAYVAOLAM) values ('2','NGUY?N VÃN TOÀN','KT','NAM',to_date('08-09-1993','DD-MM-RRRR'),'TPHCM','392715034',to_date('03-04-2018','DD-MM-RRRR'));
Insert into C##USERADMIN.NHANVIEN (MANV,TENNV,CHUCVU,GIOITINH,NGAYSINH,DIACHI,SDT,NGAYVAOLAM) values ('3','?OÀN VÃN HÙNG','BH','N?',to_date('03-12-1985','DD-MM-RRRR'),'TPHCM','928593185',to_date('30-06-2015','DD-MM-RRRR'));
Insert into C##USERADMIN.NHANVIEN (MANV,TENNV,CHUCVU,GIOITINH,NGAYSINH,DIACHI,SDT,NGAYVAOLAM) values ('4','NGUY?N TH? HOÀI THÝÕNG','TN','N?',to_date('17-08-1997','DD-MM-RRRR'),'TPHCM','928493155',to_date('09-10-2019','DD-MM-RRRR'));
Insert into C##USERADMIN.NHANVIEN (MANV,TENNV,CHUCVU,GIOITINH,NGAYSINH,DIACHI,SDT,NGAYVAOLAM) values ('5','HOÀNG VÃN TÚ','QL','NAM',to_date('14-05-1989','DD-MM-RRRR'),'TPHCM','369275023',to_date('19-01-2017','DD-MM-RRRR'));
Insert into C##USERADMIN.NHANVIEN (MANV,TENNV,CHUCVU,GIOITINH,NGAYSINH,DIACHI,SDT,NGAYVAOLAM) values ('6','NGUY?N MINH NH?T','TN','NAM',to_date('15-03-1991','DD-MM-RRRR'),'TPHCM','945237455',to_date('07-01-2020','DD-MM-RRRR'));
Insert into C##USERADMIN.NHANVIEN (MANV,TENNV,CHUCVU,GIOITINH,NGAYSINH,DIACHI,SDT,NGAYVAOLAM) values ('7','NGUY?N H?I QUÂN','QL','NAM',to_date('24-02-1997','DD-MM-RRRR'),'TPHCM','779880707',to_date('20-05-2020','DD-MM-RRRR'));
REM INSERTING into C##USERADMIN.PHIEUDV
SET DEFINE OFF;
Insert into C##USERADMIN.PHIEUDV (MAPDV,MANV,MAKH,NGAYTAOPDV,TONGSLDV,TONGTIEN,TRATRUOC,THANHTIEN) values ('1','1','1',to_date('11-02-2021','DD-MM-RRRR'),'1','5600000','3600000','2000000');
Insert into C##USERADMIN.PHIEUDV (MAPDV,MANV,MAKH,NGAYTAOPDV,TONGSLDV,TONGTIEN,TRATRUOC,THANHTIEN) values ('2','2','2',to_date('11-02-2021','DD-MM-RRRR'),'1','5650000','5000000','650000');
Insert into C##USERADMIN.PHIEUDV (MAPDV,MANV,MAKH,NGAYTAOPDV,TONGSLDV,TONGTIEN,TRATRUOC,THANHTIEN) values ('3','3','3',to_date('11-02-2021','DD-MM-RRRR'),'1','100000','100000','0');
Insert into C##USERADMIN.PHIEUDV (MAPDV,MANV,MAKH,NGAYTAOPDV,TONGSLDV,TONGTIEN,TRATRUOC,THANHTIEN) values ('4','4','4',to_date('11-02-2021','DD-MM-RRRR'),'1','250000','250000','0');
Insert into C##USERADMIN.PHIEUDV (MAPDV,MANV,MAKH,NGAYTAOPDV,TONGSLDV,TONGTIEN,TRATRUOC,THANHTIEN) values ('5','5','5',to_date('11-02-2021','DD-MM-RRRR'),'1','300000','300000','0');
REM INSERTING into C##USERADMIN.PHIEUNHAP
SET DEFINE OFF;
Insert into C##USERADMIN.PHIEUNHAP (MAPN,MANV,NGAYTAOPN,TONGSLSP) values ('6','1',to_date('25-06-2022','DD-MM-RRRR'),'78');
Insert into C##USERADMIN.PHIEUNHAP (MAPN,MANV,NGAYTAOPN,TONGSLSP) values ('1','1',to_date('01-06-2021','DD-MM-RRRR'),'12');
Insert into C##USERADMIN.PHIEUNHAP (MAPN,MANV,NGAYTAOPN,TONGSLSP) values ('2','2',to_date('02-06-2021','DD-MM-RRRR'),'14');
Insert into C##USERADMIN.PHIEUNHAP (MAPN,MANV,NGAYTAOPN,TONGSLSP) values ('3','3',to_date('03-06-2021','DD-MM-RRRR'),'19');
Insert into C##USERADMIN.PHIEUNHAP (MAPN,MANV,NGAYTAOPN,TONGSLSP) values ('4','4',to_date('04-06-2021','DD-MM-RRRR'),'10');
Insert into C##USERADMIN.PHIEUNHAP (MAPN,MANV,NGAYTAOPN,TONGSLSP) values ('5','5',to_date('05-06-2021','DD-MM-RRRR'),'9');
Insert into C##USERADMIN.PHIEUNHAP (MAPN,MANV,NGAYTAOPN,TONGSLSP) values ('7','1',to_date('25-06-2022','DD-MM-RRRR'),'32');
REM INSERTING into C##USERADMIN.SANPHAM
SET DEFINE OFF;
Insert into C##USERADMIN.SANPHAM (MASP,MALSP,TENSP,SLTON,DVT,DONGIA) values ('1','3','L?C TAY HOA CÚC','58','CÁI','2900000');
Insert into C##USERADMIN.SANPHAM (MASP,MALSP,TENSP,SLTON,DVT,DONGIA) values ('2','1','NH?N N?','19','CÁI','3000000');
Insert into C##USERADMIN.SANPHAM (MASP,MALSP,TENSP,SLTON,DVT,DONGIA) values ('3','1','NH?N NAM','18','CÁI','3000000');
Insert into C##USERADMIN.SANPHAM (MASP,MALSP,TENSP,SLTON,DVT,DONGIA) values ('4','1','NH?N CÝ?I','41','CÁI','5000000');
Insert into C##USERADMIN.SANPHAM (MASP,MALSP,TENSP,SLTON,DVT,DONGIA) values ('5','3','L?C TAY N?','19','CÁI','4000000');
Insert into C##USERADMIN.SANPHAM (MASP,MALSP,TENSP,SLTON,DVT,DONGIA) values ('6','3','L?C TAY NAM','20','CÁI','4000000');
Insert into C##USERADMIN.SANPHAM (MASP,MALSP,TENSP,SLTON,DVT,DONGIA) values ('7','2','DÂY CHUY?N M?NH','51','CÁI','4590000');
Insert into C##USERADMIN.SANPHAM (MASP,MALSP,TENSP,SLTON,DVT,DONGIA) values ('8','2','M?T D Y CHUY?N TRÁI TIM','33','CÁI','2500000');
Insert into C##USERADMIN.SANPHAM (MASP,MALSP,TENSP,SLTON,DVT,DONGIA) values ('9','5','KI?NG','18','CÁI','4600000');
Insert into C##USERADMIN.SANPHAM (MASP,MALSP,TENSP,SLTON,DVT,DONGIA) values ('10','1','NH?N','20','CÁI','2600000');
REM INSERTING into C##USERADMIN.TAIKHOAN
SET DEFINE OFF;
Insert into C##USERADMIN.TAIKHOAN (MANV,TENTK,MATKHAU) values ('1','NV01','1234567');
Insert into C##USERADMIN.TAIKHOAN (MANV,TENTK,MATKHAU) values ('7','NV07','154');
Insert into C##USERADMIN.TAIKHOAN (MANV,TENTK,MATKHAU) values ('2','NV02','123');
Insert into C##USERADMIN.TAIKHOAN (MANV,TENTK,MATKHAU) values ('3','NV03','4566');
Insert into C##USERADMIN.TAIKHOAN (MANV,TENTK,MATKHAU) values ('4','NV04','129');
Insert into C##USERADMIN.TAIKHOAN (MANV,TENTK,MATKHAU) values ('5','NV05','124');
Insert into C##USERADMIN.TAIKHOAN (MANV,TENTK,MATKHAU) values ('6','NV06','154');
--------------------------------------------------------
--  DDL for Index PK_CTDV
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_CTDV" ON "C##USERADMIN"."CTDV" ("MAPDV", "MADV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CTHD
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_CTHD" ON "C##USERADMIN"."CTHD" ("MAHD", "MASP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CTNSP
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_CTNSP" ON "C##USERADMIN"."CTNSP" ("MAPN", "MASP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_KM
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_KM" ON "C##USERADMIN"."KHUYENMAI" ("MAKM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MADT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_MADT" ON "C##USERADMIN"."DOITAC" ("MADT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MADV
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_MADV" ON "C##USERADMIN"."DICHVU" ("MADV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MAHD
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_MAHD" ON "C##USERADMIN"."HOADON" ("MAHD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MAKH
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_MAKH" ON "C##USERADMIN"."KHACHHANG" ("MAKH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MALSP
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_MALSP" ON "C##USERADMIN"."LOAISANPHAM" ("MALSP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MANV
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_MANV" ON "C##USERADMIN"."NHANVIEN" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MAPDV
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_MAPDV" ON "C##USERADMIN"."PHIEUDV" ("MAPDV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MAPN
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_MAPN" ON "C##USERADMIN"."PHIEUNHAP" ("MAPN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MASP
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_MASP" ON "C##USERADMIN"."SANPHAM" ("MASP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USERADMIN"."PK_TK" ON "C##USERADMIN"."TAIKHOAN" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CUS_REVENUE_INCREASED
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##USERADMIN"."TRIGGER_CUS_REVENUE_INCREASED" 
AFTER INSERT OR UPDATE OR DELETE ON HOADON
FOR EACH ROW
BEGIN
    IF(INSERTING) THEN
        UPDATE KHACHHANG
        SET DIEM = (DIEM + :NEW.THANHTIEN)
        WHERE MAKH = :new.MAKH;
    END IF; 
    IF(UPDATING) THEN
        UPDATE KHACHHANG
        SET DIEM = (DIEM + (:NEW.THANHTIEN - :old.THANHTIEN))
        WHERE MAKH = :new.MAKH;
    END IF; 
    IF(DELETING) THEN
        UPDATE KHACHHANG
        SET DIEM = (DIEM - :old.THANHTIEN)
        WHERE MAKH = :old.MAKH;   
    END IF;  
END;
/
ALTER TRIGGER "C##USERADMIN"."TRIGGER_CUS_REVENUE_INCREASED" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CUS_TYPE_OLD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##USERADMIN"."TRIGGER_CUS_TYPE_OLD" 
BEFORE UPDATE ON KHACHHANG
FOR EACH ROW
BEGIN  
    IF (:new.DIEM <= 5000000)
    THEN
        :new.LOAI := 'M?i';
    END IF;
    IF (:new.DIEM > 5000000 and :new.DIEM <= 15000000)
    THEN
        :new.LOAI := 'Ti?m Nãng';
    END IF;
    IF (:new.DIEM > 15000000 and :new.DIEM <= 30000000)
    THEN
        :new.LOAI := 'Thân Thi?t';
    END IF;
    IF (:new.DIEM > 30000000)
    THEN
        :new.LOAI := 'VIP';
    END IF;
END;
/
ALTER TRIGGER "C##USERADMIN"."TRIGGER_CUS_TYPE_OLD" ENABLE;
--------------------------------------------------------
--  Constraints for Table DICHVU
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."DICHVU" MODIFY ("MADV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."DICHVU" MODIFY ("TENDV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."DICHVU" MODIFY ("TIENDV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."DICHVU" ADD CONSTRAINT "PK_MADV" PRIMARY KEY ("MADV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAIKHOAN
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."TAIKHOAN" MODIFY ("TENTK" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."TAIKHOAN" MODIFY ("MATKHAU" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."TAIKHOAN" ADD CONSTRAINT "PK_TK" PRIMARY KEY ("MANV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KHUYENMAI
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."KHUYENMAI" MODIFY ("MAKM" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."KHUYENMAI" MODIFY ("LOAIKM" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."KHUYENMAI" ADD CONSTRAINT "PK_KM" PRIMARY KEY ("MAKM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOITAC
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."DOITAC" MODIFY ("MADT" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."DOITAC" MODIFY ("TENCTY" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."DOITAC" MODIFY ("DIACHI" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."DOITAC" MODIFY ("SDT" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."DOITAC" ADD CONSTRAINT "PK_MADT" PRIMARY KEY ("MADT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHIEUDV
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."PHIEUDV" MODIFY ("MAPDV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."PHIEUDV" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."PHIEUDV" MODIFY ("NGAYTAOPDV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."PHIEUDV" MODIFY ("TONGSLDV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."PHIEUDV" MODIFY ("TONGTIEN" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."PHIEUDV" MODIFY ("TRATRUOC" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."PHIEUDV" MODIFY ("THANHTIEN" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."PHIEUDV" ADD CONSTRAINT "PK_MAPDV" PRIMARY KEY ("MAPDV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SANPHAM
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."SANPHAM" MODIFY ("MASP" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."SANPHAM" MODIFY ("MALSP" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."SANPHAM" MODIFY ("TENSP" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."SANPHAM" MODIFY ("SLTON" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."SANPHAM" MODIFY ("DVT" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."SANPHAM" MODIFY ("DONGIA" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."SANPHAM" ADD CONSTRAINT "PK_MASP" PRIMARY KEY ("MASP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CTDV
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."CTDV" MODIFY ("MAPDV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."CTDV" MODIFY ("MADV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."CTDV" MODIFY ("SLDV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."CTDV" ADD CONSTRAINT "PK_CTDV" PRIMARY KEY ("MAPDV", "MADV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOADON
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."HOADON" MODIFY ("MAHD" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."HOADON" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."HOADON" MODIFY ("NGAYTAOHD" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."HOADON" MODIFY ("TONGTIEN" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."HOADON" MODIFY ("THANHTIEN" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."HOADON" ADD CONSTRAINT "PK_MAHD" PRIMARY KEY ("MAHD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KHACHHANG
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."KHACHHANG" MODIFY ("MAKH" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."KHACHHANG" MODIFY ("TENKH" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."KHACHHANG" MODIFY ("GIOITINH" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."KHACHHANG" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."KHACHHANG" MODIFY ("SDT" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."KHACHHANG" MODIFY ("DIEM" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."KHACHHANG" MODIFY ("LOAI" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."KHACHHANG" MODIFY ("NGAYSINH" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."KHACHHANG" ADD CONSTRAINT "PK_MAKH" PRIMARY KEY ("MAKH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHIEUNHAP
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."PHIEUNHAP" MODIFY ("MAPN" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."PHIEUNHAP" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."PHIEUNHAP" MODIFY ("NGAYTAOPN" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."PHIEUNHAP" MODIFY ("TONGSLSP" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."PHIEUNHAP" ADD CONSTRAINT "PK_MAPN" PRIMARY KEY ("MAPN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CTNSP
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."CTNSP" MODIFY ("MAPN" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."CTNSP" MODIFY ("MASP" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."CTNSP" MODIFY ("MADT" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."CTNSP" MODIFY ("SLNHAP" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."CTNSP" MODIFY ("DONGIANHAP" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."CTNSP" MODIFY ("THANHTIEN" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."CTNSP" ADD CONSTRAINT "PK_CTNSP" PRIMARY KEY ("MAPN", "MASP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CTHD
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."CTHD" MODIFY ("MAHD" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."CTHD" MODIFY ("MASP" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."CTHD" MODIFY ("SLSP" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."CTHD" ADD CONSTRAINT "PK_CTHD" PRIMARY KEY ("MAHD", "MASP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOAISANPHAM
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."LOAISANPHAM" MODIFY ("MALSP" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."LOAISANPHAM" MODIFY ("TENLSP" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."LOAISANPHAM" ADD CONSTRAINT "PK_MALSP" PRIMARY KEY ("MALSP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NHANVIEN
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."NHANVIEN" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."NHANVIEN" MODIFY ("TENNV" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."NHANVIEN" MODIFY ("CHUCVU" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."NHANVIEN" MODIFY ("GIOITINH" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."NHANVIEN" MODIFY ("NGAYSINH" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."NHANVIEN" MODIFY ("DIACHI" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."NHANVIEN" MODIFY ("SDT" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."NHANVIEN" MODIFY ("NGAYVAOLAM" NOT NULL ENABLE);
  ALTER TABLE "C##USERADMIN"."NHANVIEN" ADD CONSTRAINT "PK_MANV" PRIMARY KEY ("MANV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CTDV
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."CTDV" ADD CONSTRAINT "FK_MADV_CTDV" FOREIGN KEY ("MADV")
	  REFERENCES "C##USERADMIN"."DICHVU" ("MADV") ENABLE;
  ALTER TABLE "C##USERADMIN"."CTDV" ADD CONSTRAINT "FK_MAPDV_CTDV" FOREIGN KEY ("MAPDV")
	  REFERENCES "C##USERADMIN"."PHIEUDV" ("MAPDV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CTHD
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."CTHD" ADD CONSTRAINT "FK_MAHD_CTHD" FOREIGN KEY ("MAHD")
	  REFERENCES "C##USERADMIN"."HOADON" ("MAHD") ENABLE;
  ALTER TABLE "C##USERADMIN"."CTHD" ADD CONSTRAINT "FK_MASP_CTHD" FOREIGN KEY ("MASP")
	  REFERENCES "C##USERADMIN"."SANPHAM" ("MASP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CTNSP
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."CTNSP" ADD CONSTRAINT "FK_MADT_CTN" FOREIGN KEY ("MADT")
	  REFERENCES "C##USERADMIN"."DOITAC" ("MADT") ENABLE;
  ALTER TABLE "C##USERADMIN"."CTNSP" ADD CONSTRAINT "FK_MASP_CTN" FOREIGN KEY ("MASP")
	  REFERENCES "C##USERADMIN"."SANPHAM" ("MASP") ENABLE;
  ALTER TABLE "C##USERADMIN"."CTNSP" ADD CONSTRAINT "FK_MAPN_CTN" FOREIGN KEY ("MAPN")
	  REFERENCES "C##USERADMIN"."PHIEUNHAP" ("MAPN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOADON
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."HOADON" ADD CONSTRAINT "FK_MANV_HD" FOREIGN KEY ("MANV")
	  REFERENCES "C##USERADMIN"."NHANVIEN" ("MANV") ENABLE;
  ALTER TABLE "C##USERADMIN"."HOADON" ADD CONSTRAINT "FK_MAKH" FOREIGN KEY ("MAKH")
	  REFERENCES "C##USERADMIN"."KHACHHANG" ("MAKH") ENABLE;
  ALTER TABLE "C##USERADMIN"."HOADON" ADD CONSTRAINT "FK_MAKM" FOREIGN KEY ("MAKM")
	  REFERENCES "C##USERADMIN"."KHUYENMAI" ("MAKM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHIEUDV
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."PHIEUDV" ADD CONSTRAINT "FK_MAKH_PDV" FOREIGN KEY ("MAKH")
	  REFERENCES "C##USERADMIN"."KHACHHANG" ("MAKH") ENABLE;
  ALTER TABLE "C##USERADMIN"."PHIEUDV" ADD CONSTRAINT "FK_MANV_PDV" FOREIGN KEY ("MANV")
	  REFERENCES "C##USERADMIN"."NHANVIEN" ("MANV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHIEUNHAP
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."PHIEUNHAP" ADD CONSTRAINT "FK_MANV" FOREIGN KEY ("MANV")
	  REFERENCES "C##USERADMIN"."NHANVIEN" ("MANV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SANPHAM
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."SANPHAM" ADD CONSTRAINT "FK_MALSP" FOREIGN KEY ("MALSP")
	  REFERENCES "C##USERADMIN"."LOAISANPHAM" ("MALSP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAIKHOAN
--------------------------------------------------------

  ALTER TABLE "C##USERADMIN"."TAIKHOAN" ADD CONSTRAINT "FK_MANV_TK" FOREIGN KEY ("MANV")
	  REFERENCES "C##USERADMIN"."NHANVIEN" ("MANV") ENABLE;
