/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class QuanLyPhieuNhap extends javax.swing.JFrame {

    DefaultTableModel tableQLNH = new DefaultTableModel();
    DefaultTableModel tableCTNSP = new DefaultTableModel();

    /**
     * Creates new form QuanLyNhapHang1
     */
    public QuanLyPhieuNhap() {
        initComponents();
        setListPN();
        setVisible(true);
    }

    public void setListPN() {
        String tieuDe[] = {"MaPN", "MANV", "NGAYTAO", "TONGSLSP"};
        String tieuDe2[] = {"MaPN", "MASP", "MADT", "SLN", "DONGIA", "THANHTIEN"};
        tableQLNH.setColumnIdentifiers(tieuDe);
        tableCTNSP.setColumnIdentifiers(tieuDe2);

        try {
            Connection conn = null;
            conn = ConnectionUtils.getMyConnection();
            String SQL = "SELECT * FROM PHIEUNHAP ORDER BY MaPN DESC";
            PreparedStatement ps = conn.prepareStatement(SQL);
            ResultSet rs = ps.executeQuery();
            String row[] = new String[4];
            while (rs.next()) {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);

                tableQLNH.addRow(row);

            }
        } catch (SQLException ex) {
            System.out.println("Xay ra loi");
        } catch (ClassNotFoundException cx) {

        }
        bang1.setModel(tableQLNH);
        bang2.setModel(tableCTNSP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MP = new javax.swing.JTextField();
        AddReport = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bang1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        bang2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã phiếu");

        MP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPActionPerformed(evt);
            }
        });

        AddReport.setText("Tạo phiếu nhập");
        AddReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddReportActionPerformed(evt);
            }
        });

        Xoa.setText("Xóa");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        bang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bang1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bang1);

        bang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(bang2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(AddReport)
                        .addGap(49, 49, 49)
                        .addComponent(Xoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddReport)
                    .addComponent(Xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddReportActionPerformed
        Connection conn = null;
        try {
            conn = ConnectionUtils.getMyConnection();
            String SQL = "INSERT INTO PHIEUNHAP(MAPN, MANV, NGAYTAOPN, TONGSLSP) VALUES(mapn_seq.nextval, ?, TO_DATE(CURRENT_DATE, 'DD-MM-YYYY HH24:MI:SS'),0)";
            PreparedStatement ps = conn.prepareStatement(SQL);
            ps.setInt(1, 3);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thêm thành công !!!");
//            this.dispose();
//            ChonSanPhamNhap.main(null);
        } catch (SQLException ex) {
            System.out.println(ex);
            System.out.println("Xảy ra lỗi!");
        } catch (ClassNotFoundException cx) {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_AddReportActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        Connection conn = null;
        try {
            // điều kiện mà makh dc r j tùm lum v chị makh trùng đc mầm mã kh mà trùng
            // khúc thêm vô á, makh trùng vẫn ok ủa nó là khóa mà sao trùng chị tự tạo bảng à
            //cop từ cái e gửi mà
            conn = ConnectionUtils.getMyConnection();
            String SQL = "DELETE FROM PHIEUNHAP "
                    + "WHERE MAPN = ? ";
            PreparedStatement ps = conn.prepareStatement(SQL);
            ps.setString(1, bang1.getValueAt(bang1.getSelectedRow(), 0).toString());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Xóa thành công !!!");

        } catch (SQLException ex) {
            System.out.println(ex);
            System.out.println("Xảy ra lỗi!");
        } catch (ClassNotFoundException cx) {

        }           // TODO add your handling code here:
    }//GEN-LAST:event_XoaActionPerformed

    private void bang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bang1MouseClicked
        try {
            Connection conn = null;
            conn = ConnectionUtils.getMyConnection();
            String SQL = "SELECT * FROM CTNSP ORDER BY MaPN";
            PreparedStatement ps = conn.prepareStatement(SQL);
            ResultSet rs = ps.executeQuery();
            String row[] = new String[6];
            while (rs.next()) {
                String MaSP = tableQLNH.getValueAt(bang1.getSelectedRow(), 0).toString();
                row[0] = MaSP;
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                row[5] = rs.getString(6);

                tableCTNSP.addRow(row);

            }
        } catch (SQLException ex) {
            System.out.println("Xay ra loi");
        } catch (ClassNotFoundException cx) {

        }
        MP.setText(bang1.getValueAt(bang1.getSelectedRow(), 0).toString());

        bang2.setModel(tableCTNSP);

        setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bang1MouseClicked

    private void MPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddReport;
    private javax.swing.JTextField MP;
    private javax.swing.JButton Xoa;
    private javax.swing.JTable bang1;
    private javax.swing.JTable bang2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
