/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class TaoPhieuNhap extends javax.swing.JFrame {

    int maPN = -1;
    /**
     * Creates new form ChonSanPhamNhap
     */

    DefaultTableModel tableDanhSachSP = new DefaultTableModel(), tableDanhSachSP1 = new DefaultTableModel(), tableDanhSachDT = new DefaultTableModel();

    public TaoPhieuNhap() {
        initComponents();
        loadBang();
        setMaPN();
        setVisible(true);
    }

    public void setMaPN() {
        try {
            Connection conn = null;
            conn = (Connection) DoAn_CuaHangDaQuy.getMyConnection();
            String SQL = "SELECT MAPN FROM PHIEUNHAP ORDER BY MAPN DESC";
            PreparedStatement ps = conn.prepareStatement(SQL);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                maPhieuNhap.setText(rs.getString(1));
                maPN = Integer.valueOf(rs.getString(1));

            }
        } catch (SQLException ex) {
            System.out.println("Xay ra loi");
        } catch (ClassNotFoundException cx) {

        }
    }

    public void loadBang() {
        String tieuDe[] = {"MASP", "MALSP", "TenSP", "SLTon", "DVT", "DonGia"};
        String tieuDe3[] = {"MADT", "TENCTY"};

        String tieuDe1[] = {"MASP", "MaDT", "TenSP", "DVT", "DonGiaNhap", "SoluongNhap", "ThanhTien"};
        tableDanhSachSP.setColumnIdentifiers(tieuDe);
        tableDanhSachSP1.setColumnIdentifiers(tieuDe1);
        tableDanhSachDT.setColumnIdentifiers(tieuDe3);
        try {
            Connection conn = null;
            conn = (Connection) DoAn_CuaHangDaQuy.getMyConnection();
            String SQL = "SELECT * FROM SANPHAM ORDER BY MaSP";
            PreparedStatement ps = conn.prepareStatement(SQL);
            ResultSet rs = ps.executeQuery();
            String row[] = new String[6];
            while (rs.next()) {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                row[5] = rs.getString(6);

                tableDanhSachSP.addRow(row);

            }
        } catch (SQLException ex) {
            System.out.println("Xay ra loi");
        } catch (ClassNotFoundException cx) {

        }
        try {
            Connection conn = null;
            conn = (Connection) DoAn_CuaHangDaQuy.getMyConnection();
            String SQL = "SELECT * FROM DOITAC ORDER BY MADT";
            PreparedStatement ps = conn.prepareStatement(SQL);
            ResultSet rs = ps.executeQuery();
            String row[] = new String[4];
            while (rs.next()) {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);

                tableDanhSachDT.addRow(row);

            }
        } catch (SQLException ex) {
            System.out.println("Xay ra loi");
        } catch (ClassNotFoundException cx) {

        }

        Bang1.setModel(tableDanhSachSP);
        Bang2.setModel(tableDanhSachSP1);
        bang3.setModel(tableDanhSachDT);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Bang1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Bang2 = new javax.swing.JTable();
        DonGia = new javax.swing.JTextField();
        SoLuong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        them = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TongCong = new javax.swing.JTextField();
        quaylai = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        maPhieuNhap = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        taophieunhap = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        bang3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Bang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bang1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Bang1);

        Bang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Bang2);

        jLabel1.setText("Đơn giá nhập");

        jLabel2.setText("Số lượng");

        them.setText("thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        jLabel3.setText("Tổng Cộng ");

        TongCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TongCongActionPerformed(evt);
            }
        });

        quaylai.setText("Quay lại");
        quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaylaiActionPerformed(evt);
            }
        });

        jLabel4.setText("Mã Phiếu Nhập");

        maPhieuNhap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        maPhieuNhap.setForeground(new java.awt.Color(255, 51, 51));
        maPhieuNhap.setText("0");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 102));
        jLabel6.setText("Chi Tiết Phiếu Nhập");

        taophieunhap.setText("Tạo phiếu nhập");
        taophieunhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taophieunhapActionPerformed(evt);
            }
        });

        bang3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(bang3);

        jLabel5.setText("Mã Đối Tác");

        jFormattedTextField1.setEditable(false);

        jButton1.setText("Xóa lựa chọn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel6)
                .addGap(0, 561, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(maPhieuNhap))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quaylai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)
                                .addComponent(TongCong, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(taophieunhap))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(them)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(DonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                        .addComponent(SoLuong))
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maPhieuNhap))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(TongCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(quaylai)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taophieunhap)))
                .addGap(437, 437, 437))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bang1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModelChuyen, tableModelNhan = new DefaultTableModel();
        tableModelChuyen = (DefaultTableModel) Bang1.getModel();
        String MaSP = tableModelChuyen.getValueAt(Bang1.getSelectedRow(), 0).toString();
        String MaLSP = tableModelChuyen.getValueAt(Bang1.getSelectedRow(), 1).toString();
        String TenSP = tableModelChuyen.getValueAt(Bang1.getSelectedRow(), 2).toString();
        String DVT = tableModelChuyen.getValueAt(Bang1.getSelectedRow(), 4).toString();
        Double ThanhTien = Double.parseDouble(DonGia.getText().toString()) * Double.valueOf(SoLuong.getText().toString());
        tableModelNhan = (DefaultTableModel) Bang2.getModel();
        tableModelNhan.addRow(new Object[]{MaSP, MaLSP, TenSP, DVT, DonGia.getText().toString(),
            SoLuong.getText().toString(), ThanhTien.toString()});
        Double tong = 0.0;

        for (int i = 0; i < tableModelNhan.getRowCount(); i++) {
            tong = Double.valueOf(tableModelNhan.getValueAt(i, 6).toString()) + tong;
        }
        TongCong.setText(String.valueOf(tong));


    }//GEN-LAST:event_Bang1MouseClicked

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        Connection conn = null;
        try {
            DefaultTableModel tableModelNhan = new DefaultTableModel();
            tableModelNhan = (DefaultTableModel) Bang2.getModel();
            String MaLSP = tableModelNhan.getValueAt(Bang2.getSelectedRow(), 5).toString();

            conn = (Connection) DoAn_CuaHangDaQuy.getMyConnection();
            String SQL = "INSERT INTO PHIEUNHAP(MaNV,NgayTaoPN,TongSLSP) VALUES( ?,getdate(),?)";
            PreparedStatement ps = conn.prepareStatement(SQL);

            ps.setString(1, "2");
            ps.setString(2, MaLSP);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thêm thành công !!!");
        } catch (SQLException ex) {
            System.out.println(ex);
            System.out.println("Xảy ra lỗi!");
        } catch (ClassNotFoundException cx) {

        }
        // TODO add your handling code here:

    }//GEN-LAST:event_themActionPerformed

    private void TongCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TongCongActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_TongCongActionPerformed

    private void quaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaylaiActionPerformed
        this.setVisible(false);
        new TaoPhieuNhapHang().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_quaylaiActionPerformed

    private void taophieunhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taophieunhapActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        try {
            DefaultTableModel tableModelNhan = new DefaultTableModel();
            DefaultTableModel tableModelNhan2 = new DefaultTableModel();

            tableModelNhan = (DefaultTableModel) Bang2.getModel();
            String MaSP = tableModelNhan.getValueAt(Bang2.getSelectedRow(), 0).toString();
            String SLN = tableModelNhan.getValueAt(Bang2.getSelectedRow(), 5).toString();

            String MaDT = tableModelNhan2.getValueAt(bang3.getSelectedRow(), 0).toString();
            String DonGia = tableModelNhan.getValueAt(Bang2.getSelectedRow(), 4).toString();
            String ThanhTien = tableModelNhan.getValueAt(Bang2.getSelectedRow(), 6).toString();

            conn = (Connection) DoAn_CuaHangDaQuy.getMyConnection();
            String SQL = "INSERT INTO CTNSP VALUES( ?,?,?,?,?,?)";
            PreparedStatement ps = conn.prepareStatement(SQL);

            ps.setString(1, maPhieuNhap.getText());
            ps.setString(2, MaSP);
            ps.setString(3, MaDT);
            ps.setString(4, SLN);
            ps.setString(5, DonGia);
            ps.setString(6, ThanhTien);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thêm thành công !!!");
        } catch (SQLException ex) {
            System.out.println(ex);
            System.out.println("Xảy ra lỗi!");
        } catch (ClassNotFoundException cx) {

        }
    }//GEN-LAST:event_taophieunhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoPhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Bang1;
    private javax.swing.JTable Bang2;
    private javax.swing.JTextField DonGia;
    private javax.swing.JTextField SoLuong;
    private javax.swing.JTextField TongCong;
    private javax.swing.JTable bang3;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel maPhieuNhap;
    private javax.swing.JButton quaylai;
    private javax.swing.JButton taophieunhap;
    private javax.swing.JButton them;
    // End of variables declaration//GEN-END:variables
}
