/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Process.PhieuDichVu;
import Process.KhachHang;
import Process.DichVu;
import java.io.UnsupportedEncodingException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thetu
 */
public class TaoPhieuDichVu extends javax.swing.JFrame {

    DefaultTableModel DSDV = new DefaultTableModel();
    int maDV = -1;

    DefaultTableModel DSKH = new DefaultTableModel();
    DefaultTableModel DSSPC = new DefaultTableModel();
    String SPDC[] = new String[7];
    float TongTien = 0;
    int traTruoc = 0;
    int tongSLDV = 0;

    int maKH = -1;
    int maPDV = -1;

    /**
     * Creates new form TaoPhieuDichVu
     */
    public TaoPhieuDichVu() {
        initComponents();
        setListDV();
        setListKH();
        setMaPDV();
    }
    
    private void setMaPDV() {
        try {
            PhieuDichVu pdv = new PhieuDichVu();
            ResultSet rs = pdv.getMaPDV();
            if (rs.next()) {
                maHoaDon.setText(rs.getString(1));
                maPDV = Integer.valueOf(rs.getString(1));

            }

        } catch (SQLException | ClassNotFoundException ex) {
            System.out.println("Xay ra loi");
        }
    }

    private void setListDV() {
        try {
            DichVu dv = new DichVu();
            ResultSet rs = dv.getListDV();
            DSDV = (DefaultTableModel) bang2.getModel();
            DSDV.setRowCount(0);
            String row[] = new String[6];
            while (rs.next()) {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);

                DSDV.addRow(row);
            }
            bang2.setModel(DSDV);

        } catch (SQLException | ClassNotFoundException ex) {
            System.out.println("Xay ra loi");
        }
    }

    private void setListKH() {
        try {
            KhachHang kh = new KhachHang();
            ResultSet rs = kh.getListKH();
            DSKH = (DefaultTableModel) bang1.getModel();
            DSKH.setRowCount(0);
            String row[] = new String[4];
            while (rs.next()) {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                DSKH.addRow(row);
            }
            bang1.setModel(DSKH);

        } catch (SQLException | ClassNotFoundException ex) {
            System.out.println("Xay ra loi");
        }
    }

    private void addCTDV() {
        // add CTHD
        int countResult = 0;
        for (int i = 0; i < DSSPC.getRowCount(); i++) {
            try {
                int MDV = Integer.valueOf(DSSPC.getValueAt(i, 0).toString());
                int SL = Integer.valueOf(DSSPC.getValueAt(i, 3).toString());
                //System.out.println("\n" + maHD + "    " + MSP + "   " + SL);
                PhieuDichVu pdv = new PhieuDichVu();
                int check = pdv.addCTDV(maPDV, MDV, SL);
                countResult++;
                tongSLDV = tongSLDV + countResult;
            } catch (SQLException ex) {
                System.out.println(ex);
                System.out.println("Xảy ra lỗi!");

            } catch (ClassNotFoundException cx) {

            }
        }
        System.out.println(countResult);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bang2 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        abc = new javax.swing.JLabel();
        maSPC = new javax.swing.JFormattedTextField();
        huyHoaDon = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tenSPC = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        thanhTien = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        tenKhachHang = new javax.swing.JFormattedTextField();
        tongKhuyenMai = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tongTien = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bang1 = new javax.swing.JTable();
        chonLai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        themVaoHoaDon = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        soLC = new javax.swing.JFormattedTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        bang4 = new javax.swing.JTable();
        jSlider1 = new javax.swing.JSlider(1, 10, 1);
        maHoaDon = new javax.swing.JLabel();
        thanhToan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tạo Phiếu Dịch Vụ");

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        bang2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã", "Tên Dịch Vụ", "Tiền Dịch Vụ"
            }
        ));
        bang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bang2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bang2);
        if (bang2.getColumnModel().getColumnCount() > 0) {
            bang2.getColumnModel().getColumn(0).setMinWidth(80);
            bang2.getColumnModel().getColumn(0).setPreferredWidth(80);
            bang2.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        jLabel17.setText("Mã dịch vụ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Số lượng");

        abc.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        abc.setForeground(new java.awt.Color(255, 0, 51));
        abc.setText("Tạo Phiếu Dịch Vụ");

        maSPC.setEditable(false);

        huyHoaDon.setBackground(new java.awt.Color(255, 0, 0));
        huyHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        huyHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        huyHoaDon.setText("Hủy Hóa Đơn");
        huyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyHoaDonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("VND");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("VND");

        tenSPC.setEditable(false);

        jLabel18.setText("10");

        jLabel8.setText("1");

        thanhTien.setEditable(false);
        thanhTien.setText("0");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Thành Tiền");

        tenKhachHang.setEditable(false);

        tongKhuyenMai.setEditable(false);
        tongKhuyenMai.setText("0");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Trả Trước");

        jLabel5.setText("Tên khách hàng");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("VND");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Danh Sách Khách Hàng");

        tongTien.setEditable(false);
        tongTien.setText("0");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Tổng Tiền");

        bang1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Mail"
            }
        ));
        bang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bang1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bang1);
        if (bang1.getColumnModel().getColumnCount() > 0) {
            bang1.getColumnModel().getColumn(0).setMinWidth(80);
            bang1.getColumnModel().getColumn(0).setPreferredWidth(80);
            bang1.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        chonLai.setBackground(new java.awt.Color(255, 102, 102));
        chonLai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chonLai.setForeground(new java.awt.Color(255, 255, 255));
        chonLai.setText("Chọn Lại");
        chonLai.setEnabled(false);
        chonLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonLaiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Dịch Vụ Đã Chọn");

        themVaoHoaDon.setBackground(new java.awt.Color(0, 255, 0));
        themVaoHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        themVaoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        themVaoHoaDon.setText("Thêm Vào Phiếu DV");
        themVaoHoaDon.setEnabled(false);
        themVaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themVaoHoaDonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Sản phẩm đang chọn");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Danh Sách Dịch Vụ");

        soLC.setText("1");
        soLC.setEnabled(false);

        bang4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bang4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên Dịch Vụ", "Tiền Dịch Vụ", "SL"
            }
        ));
        bang4.setEnabled(false);
        jScrollPane5.setViewportView(bang4);

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        maHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        maHoaDon.setForeground(new java.awt.Color(255, 51, 51));
        maHoaDon.setText("0");

        thanhToan.setBackground(new java.awt.Color(51, 51, 255));
        thanhToan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thanhToan.setForeground(new java.awt.Color(255, 255, 255));
        thanhToan.setText("Thanh Toán");
        thanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(442, 442, 442)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(83, 83, 83)
                                        .addComponent(soLC, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(173, 173, 173)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(201, 201, 201)
                                        .addComponent(themVaoHoaDon))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(maSPC, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tenSPC, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(555, 555, 555)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(abc)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(chonLai))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addGap(18, 18, 18)
                                            .addComponent(maHoaDon))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(147, 147, 147)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(thanhToan)
                                                        .addGap(11, 11, 11))
                                                    .addComponent(huyHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(97, 97, 97))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel11)
                                                            .addComponent(jLabel13)))
                                                    .addComponent(jLabel14))
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(tongKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(29, 29, 29))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(thanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(209, 209, 209)))))
                        .addContainerGap(80, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(abc)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(chonLai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(tongKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(thanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(34, 34, 34)
                                .addComponent(thanhToan)
                                .addGap(26, 26, 26)
                                .addComponent(huyHoaDon))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(maHoaDon))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tenSPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maSPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soLC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themVaoHoaDon)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bang2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bang2MouseClicked
        // TODO add your handling code here:
        soLC.setEnabled(true);
        themVaoHoaDon.setEnabled(true);
        int indexTB = bang2.getSelectedRow();
        if (indexTB < DSDV.getRowCount() && indexTB >= 0) {
            String row[] = new String[2];
            row[0] = DSDV.getValueAt(indexTB, 0).toString();;
            row[1] = DSDV.getValueAt(indexTB, 1).toString();
            maSPC.setValue(row[0]);
            tenSPC.setValue(row[1]);
            SPDC[0] = DSDV.getValueAt(bang2.getSelectedRow(), 0).toString();
            SPDC[1] = DSDV.getValueAt(bang2.getSelectedRow(), 1).toString();
            SPDC[2] = DSDV.getValueAt(bang2.getSelectedRow(), 2).toString();
            //        int temp = Integer.parseInt(soL) * Integer.parseInt(donG);
            //        SPDC[6] = String.valueOf(temp);
        }
        //        DefaultTableModel tableModelChuyen, tableModelNhan = new DefaultTableModel();
        //        tableModelChuyen = (DefaultTableModel) bang2.getModel();
        //        String maSP = tableModelChuyen.getValueAt(bang2.getSelectedRow(), 0).toString();
        //        String tenSP = tableModelChuyen.getValueAt(bang2.getSelectedRow(), 1).toString();
        //        String loaiSP = tableModelChuyen.getValueAt(bang2.getSelectedRow(), 2).toString();
        //        String soL = "1";
        //        String donV = tableModelChuyen.getValueAt(bang2.getSelectedRow(), 4).toString();
        //        String donG = tableModelChuyen.getValueAt(bang2.getSelectedRow(), 5).toString();
        //        int temp = Integer.parseInt(soL) * Integer.parseInt(donG);
        //        String thanhT = String.valueOf(temp);
        //
        //        tableModelNhan = (DefaultTableModel) bang4.getModel();
        //        tableModelNhan.addRow(new Object[]{maSP, tenSP, loaiSP, soL, donV, donG, thanhT});
        //        int indexTB = bang2.getSelectedRow();
        //        if (indexTB < DSSP.getRowCount() && indexTB >= 0) {
            //            DSSP.removeRow(indexTB);
            //        }
    }//GEN-LAST:event_bang2MouseClicked

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        System.out.println( jSlider1.getValue());
        soLC.setText(String.valueOf(jSlider1.getValue()));
    }//GEN-LAST:event_jSlider1StateChanged

    private void themVaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themVaoHoaDonActionPerformed
        // TODO add your handling code here:
        if (soLC.getText().equals("") || soLC.getText().equals(" ") || soLC.getText().equals("  ")) {
            JOptionPane.showMessageDialog(this, "Số lượng không được để trống !!!");
            return;
        }
        String tempSS = soLC.getText();
        int a = Integer.parseInt(SPDC[2]), b = Integer.parseInt(tempSS);
        
        int temp = Integer.parseInt(SPDC[2]) * b;
        TongTien += temp;
        tongTien.setText(String.valueOf(TongTien));
        DSSPC = (DefaultTableModel) bang4.getModel();
        DSSPC.addRow(new Object[]{SPDC[0], SPDC[1], SPDC[2], b});
        int indexTB = bang2.getSelectedRow();
        themVaoHoaDon.setEnabled(false);
        if (indexTB < DSDV.getRowCount() && indexTB >= 0) {
            DSDV.removeRow(indexTB);
        }
        soLC.setText("1");
        chonLai.setEnabled(true);
    }//GEN-LAST:event_themVaoHoaDonActionPerformed

    private void chonLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonLaiActionPerformed
        // TODO add your handling code here:
        int ret = 0;
        ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn chọn lại", "Chọn lại", JOptionPane.YES_NO_OPTION);
        if (!(ret == JOptionPane.YES_OPTION)) {
            return;
        }
        DSSPC.setRowCount(0);
        DSDV.setRowCount(0);
        setListDV();
        tongTien.setText("0");
        tongKhuyenMai.setText("0");
        thanhTien.setText("0");
        tongSLDV = 0;
    }//GEN-LAST:event_chonLaiActionPerformed

    private void huyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyHoaDonActionPerformed
        // TODO add your handling code here:
        try {

            PhieuDichVu pdv = new PhieuDichVu();
            int rs = pdv.remotePDV(maPDV);
            JOptionPane.showMessageDialog(this, "Xóa thành công !!!");
            this.dispose();
            QuanLyPhieuDichVu.main(null);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Xóa thất bại !!!");
        }
    }//GEN-LAST:event_huyHoaDonActionPerformed

    private void thanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhToanActionPerformed
        // TODO add your handling code here:
        //update hoa don
        String tongT = tongTien.getText();
        String tongKM = tongKhuyenMai.getText();
        String thanhT = thanhTien.getText();
        String tenKH = tenKhachHang.getText();
        if (tenKH.equals("")) {
            JOptionPane.showMessageDialog(this, "Chọn khách hàng !!!");
            return;
        }
        int ret = 0;
        ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn Thanh Toán ?", "Thanh Toán", JOptionPane.YES_NO_OPTION);
        if (!(ret == JOptionPane.YES_OPTION)) {
            return;
        }
        try {
            PhieuDichVu pdv = new PhieuDichVu();
            int check = pdv.updatePDV(maPDV, maKH, tongSLDV, tongT, tongKM, thanhT);
            if (check == 0) {
                JOptionPane.showMessageDialog(this, "Thanh toán thành thất bại !!!");
                return;
            }
            JOptionPane.showMessageDialog(this, "Thanh toán thành công !!!");
            addCTDV();
            this.dispose();
            QuanLyPhieuDichVu.main(null);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Thanh toán thành thất bại  !!!");
        }

    }//GEN-LAST:event_thanhToanActionPerformed

    private void bang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bang1MouseClicked
        // TODO add your handling code here:
        int Index = bang1.getSelectedRow();
        if (Index < DSKH.getRowCount() && Index >= 0) {
            maKH = Integer.valueOf(DSKH.getValueAt(Index, 0).toString());
            tenKhachHang.setText(DSKH.getValueAt(Index, 1).toString());
            System.out.println(maKH);
        }
    }//GEN-LAST:event_bang1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoPhieuDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoPhieuDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoPhieuDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoPhieuDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoPhieuDichVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abc;
    private javax.swing.JTable bang1;
    private javax.swing.JTable bang2;
    private javax.swing.JTable bang4;
    private javax.swing.JButton chonLai;
    private javax.swing.JButton huyHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel maHoaDon;
    private javax.swing.JFormattedTextField maSPC;
    private javax.swing.JFormattedTextField soLC;
    private javax.swing.JFormattedTextField tenKhachHang;
    private javax.swing.JFormattedTextField tenSPC;
    private javax.swing.JFormattedTextField thanhTien;
    private javax.swing.JButton thanhToan;
    private javax.swing.JButton themVaoHoaDon;
    private javax.swing.JFormattedTextField tongKhuyenMai;
    private javax.swing.JFormattedTextField tongTien;
    // End of variables declaration//GEN-END:variables
}
