/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import Process.HoaDon;
import Process.PhieuNhap;
import Process.SanPham;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class TaoPhieuNhap extends javax.swing.JFrame {

    String SPDC[] = new String[5];
    DefaultTableModel DSDT = new DefaultTableModel();
    DefaultTableModel DSSP = new DefaultTableModel();
    DefaultTableModel DSSPC = new DefaultTableModel();
    int maPN = -1;
    int maDT = -1;
    int maSP = -1;
    int TongTien = 0;

    /**
     * Creates new form ChonSanPhamNhap
     */
    public TaoPhieuNhap() {
        initComponents();
        loadDT();
        setMaPN();
        setListSP();
        setVisible(true);
    }

    public void setMaPN() {
        try {
            Connection conn = null;
            conn = ConnectionUtils.getMyConnection();
            String SQL = "SELECT MAPN FROM PHIEUNHAP ORDER BY MAPN DESC";
            PreparedStatement ps = conn.prepareStatement(SQL);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                maPhieuNhap.setText(rs.getString(1));
                maPN = Integer.valueOf(rs.getString(1));

            }
        } catch (SQLException ex) {
            System.out.println("Xay ra loi");
        } catch (ClassNotFoundException cx) {

        }
    }

    private void setListSP() {
        try {
            SanPham sp = new SanPham();
            ResultSet rs = sp.getListSP();
            DSSP = (DefaultTableModel) bang1.getModel();
            DSSP.setRowCount(0);
            String row[] = new String[6];
            while (rs.next()) {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                row[5] = rs.getString(6);
                DSSP.addRow(row);
            }
            bang1.setModel(DSSP);

        } catch (SQLException | ClassNotFoundException ex) {
            System.out.println("Xay ra loi");
        }
    }

    public void loadDT() {
        DSDT = (DefaultTableModel) bang3.getModel();
        DSDT.setRowCount(0);
        try {
            Connection conn = null;
            conn = ConnectionUtils.getMyConnection();
            String SQL = "SELECT * FROM DOITAC ORDER BY MADT";
            PreparedStatement ps = conn.prepareStatement(SQL);
            ResultSet rs = ps.executeQuery();
            String row[] = new String[4];
            while (rs.next()) {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                DSDT.addRow(row);
            }
        } catch (SQLException ex) {
            System.out.println("Xay ra loi");
        } catch (ClassNotFoundException cx) {
        }
        bang3.setModel(DSDT);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        soLuong = new javax.swing.JTextField();
        maDoiTac = new javax.swing.JFormattedTextField();
        huy = new javax.swing.JButton();
        donGiaNhap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tongCong = new javax.swing.JLabel();
        themVaoPhieuNhap = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        bang3 = new javax.swing.JTable();
        taophieunhap = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        bang2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        maPhieuNhap = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider(0, 1000000, 1);
        jSlider1 = new javax.swing.JSlider(0, 1000, 1);
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bang1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        chonLai = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chi Tiết Phiếu Nhập");

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        soLuong.setText("1");

        maDoiTac.setEditable(false);

        huy.setBackground(new java.awt.Color(255, 0, 0));
        huy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        huy.setForeground(new java.awt.Color(255, 255, 255));
        huy.setText("Hủy Phiếu Nhập");
        huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Đối Tác");

        tongCong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tongCong.setForeground(new java.awt.Color(0, 0, 255));
        tongCong.setText("0");

        themVaoPhieuNhap.setBackground(new java.awt.Color(0, 0, 255));
        themVaoPhieuNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        themVaoPhieuNhap.setForeground(new java.awt.Color(255, 255, 255));
        themVaoPhieuNhap.setText("Thêm");
        themVaoPhieuNhap.setEnabled(false);
        themVaoPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themVaoPhieuNhapActionPerformed(evt);
            }
        });

        bang3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bang3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã DT", "Tên Đối Tác"
            }
        ));
        bang3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bang3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(bang3);
        if (bang3.getColumnModel().getColumnCount() > 0) {
            bang3.getColumnModel().getColumn(0).setMinWidth(80);
            bang3.getColumnModel().getColumn(0).setPreferredWidth(80);
            bang3.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        taophieunhap.setBackground(new java.awt.Color(51, 255, 51));
        taophieunhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        taophieunhap.setForeground(new java.awt.Color(255, 255, 255));
        taophieunhap.setText("Tạo phiếu nhập");
        taophieunhap.setEnabled(false);
        taophieunhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taophieunhapActionPerformed(evt);
            }
        });

        bang2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Mã DT", "SL Nhập", "Đơn Giá Nhập", "Thành Tiền"
            }
        ));
        jScrollPane4.setViewportView(bang2);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 102));
        jLabel6.setText("Chi Tiết Phiếu Nhập");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("VND");

        maPhieuNhap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        maPhieuNhap.setForeground(new java.awt.Color(255, 51, 51));
        maPhieuNhap.setText("0");

        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel4.setText("Mã Phiếu Nhập");

        jLabel3.setText("Tổng Sản Phẩm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Số lượng");

        bang1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên Sản Phẩm", "Loại Sản Phẩm", "Số Lượng", "Đơn Vị", "Đơn Giá"
            }
        ));
        bang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bang1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bang1);
        if (bang1.getColumnModel().getColumnCount() > 0) {
            bang1.getColumnModel().getColumn(0).setMinWidth(80);
            bang1.getColumnModel().getColumn(0).setPreferredWidth(80);
            bang1.getColumnModel().getColumn(0).setMaxWidth(80);
            bang1.getColumnModel().getColumn(3).setMinWidth(80);
            bang1.getColumnModel().getColumn(3).setPreferredWidth(80);
            bang1.getColumnModel().getColumn(3).setMaxWidth(80);
            bang1.getColumnModel().getColumn(4).setMinWidth(110);
            bang1.getColumnModel().getColumn(4).setPreferredWidth(110);
            bang1.getColumnModel().getColumn(4).setMaxWidth(110);
            bang1.getColumnModel().getColumn(5).setMinWidth(110);
            bang1.getColumnModel().getColumn(5).setPreferredWidth(110);
            bang1.getColumnModel().getColumn(5).setMaxWidth(110);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Đơn giá nhập");

        chonLai.setBackground(new java.awt.Color(255, 0, 102));
        chonLai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chonLai.setForeground(new java.awt.Color(255, 255, 255));
        chonLai.setText("Xóa lựa chọn");
        chonLai.setEnabled(false);
        chonLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonLaiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Danh Sách Sản Phẩm");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Danh Sách Đối Tác");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Chi Tiết Phiếu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(maPhieuNhap)
                        .addGap(290, 290, 290)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 406, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(396, 396, 396))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(38, 38, 38)
                                    .addComponent(maDoiTac, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addComponent(themVaoPhieuNhap))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(donGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7))
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(77, 77, 77)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tongCong)
                                .addGap(84, 84, 84))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(huy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(taophieunhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(90, 90, 90))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(chonLai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maPhieuNhap)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(maDoiTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(donGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(themVaoPhieuNhap)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tongCong))
                        .addGap(18, 18, 18)
                        .addComponent(taophieunhap)
                        .addGap(18, 18, 18)
                        .addComponent(huy))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chonLai)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void addCTNSP() {
        // add CTHD
        int countResult = 0;
        for (int i = 0; i < DSSPC.getRowCount(); i++) {
            try {
                int MSP = Integer.valueOf(DSSPC.getValueAt(i, 0).toString());
                int MDT = Integer.valueOf(DSSPC.getValueAt(i, 1).toString());
                int SL = Integer.valueOf(DSSPC.getValueAt(i, 2).toString());
                int DG = Integer.valueOf(DSSPC.getValueAt(i, 3).toString());
                float TT = Float.valueOf(DSSPC.getValueAt(i, 4).toString());
                PhieuNhap pn = new PhieuNhap();
                int check = pn.addCTNSP(maPN, MSP, MDT, SL, DG, TT);
                countResult++;
            } catch (SQLException ex) {
                System.out.println(ex);
                System.out.println("Xảy ra lỗi!");

            } catch (ClassNotFoundException cx) {

            }
        }
        System.out.println(countResult);
    }
    private void taophieunhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taophieunhapActionPerformed
        // TODO add your handling code here:
        String tongT = tongCong.getText();
        int ret = 0;
        ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn hoàn thành phiếu nhập?", "Phiếu nhập", JOptionPane.YES_NO_OPTION);
        if (!(ret == JOptionPane.YES_OPTION)) {
            return;
        }
        try {
            PhieuNhap pn = new PhieuNhap();
            int check = pn.updateHD(maPN, TongTien);
            if (check == 0) {
                JOptionPane.showMessageDialog(this, "Tạo thành thất bại !!!");
                return;
            }
            JOptionPane.showMessageDialog(this, "Tạo thành công !!!");
            addCTNSP();
            this.dispose();
            QuanLyPhieuNhap.main(null);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Thanh toán thành thất bại  !!!");
        }
    }//GEN-LAST:event_taophieunhapActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        soLuong.setText(String.valueOf(jSlider1.getValue()));
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        // TODO add your handling code here:
        donGiaNhap.setText(String.valueOf(jSlider2.getValue()));
    }//GEN-LAST:event_jSlider2StateChanged

    private void bang3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bang3MouseClicked
        // TODO add your handling code here:
        int Index = bang3.getSelectedRow();
        if (Index < DSDT.getRowCount() && Index >= 0) {
            maDT = Integer.valueOf(DSDT.getValueAt(Index, 0).toString());
            maDoiTac.setText(DSDT.getValueAt(Index, 1).toString());

        }
    }//GEN-LAST:event_bang3MouseClicked

    private void bang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bang1MouseClicked
        // TODO add your handling code here:
        themVaoPhieuNhap.setEnabled(true);
        int indexTB = bang1.getSelectedRow();
        if (indexTB < DSSP.getRowCount() && indexTB >= 0) {
            SPDC[0] = DSSP.getValueAt(bang1.getSelectedRow(), 0).toString();
            maSP = Integer.valueOf(SPDC[0]);
            System.out.print(maSP);
        }
    }//GEN-LAST:event_bang1MouseClicked

    private void themVaoPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themVaoPhieuNhapActionPerformed
        // TODO add your handling code here:
        String maDTC = maDoiTac.getText();
        if (maDTC.equals("")) {
            JOptionPane.showMessageDialog(this, "Chọn đối tác !!!");
            return;
        }
        if (soLuong.getText().equals("") || soLuong.getText().equals(" ") || soLuong.getText().equals("  ")) {
            JOptionPane.showMessageDialog(this, "Số lượng không được để trống !!!");
            return;
        }
        if (donGiaNhap.getText().equals("") || donGiaNhap.getText().equals(" ") || donGiaNhap.getText().equals("  ")) {
            JOptionPane.showMessageDialog(this, "Đơn giá không được để trống !!!");
            return;
        }

        SPDC[1] = String.valueOf(maDT);
        SPDC[2] = soLuong.getText();
        SPDC[3] = donGiaNhap.getText();
        float TT = Integer.valueOf(SPDC[2]) * Integer.valueOf(SPDC[3]);
        SPDC[4] = String.valueOf(TT);
        TongTien += Integer.valueOf(SPDC[2]);
        tongCong.setText(String.valueOf(TongTien));
        DSSPC = (DefaultTableModel) bang2.getModel();
        DSSPC.addRow(new Object[]{SPDC[0], SPDC[1], SPDC[2], SPDC[3], SPDC[4]});
        int indexTB = bang1.getSelectedRow();
        themVaoPhieuNhap.setEnabled(false);
        if (indexTB < DSSP.getRowCount() && indexTB >= 0) {
            DSSP.removeRow(indexTB);
        }
        soLuong.setText("1");
        chonLai.setEnabled(true);
        taophieunhap.setEnabled(true);
    }//GEN-LAST:event_themVaoPhieuNhapActionPerformed

    private void chonLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonLaiActionPerformed
        // TODO add your handling code here:
        int ret = 0;
        ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn chọn lại", "Chọn lại", JOptionPane.YES_NO_OPTION);
        if (!(ret == JOptionPane.YES_OPTION)) {
            return;
        }
        DSSPC.setRowCount(0);
        DSSP.setRowCount(0);
        setListSP();
        tongCong.setText("0");
        TongTien = 0;
    }//GEN-LAST:event_chonLaiActionPerformed

    private void huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        try {

            conn = ConnectionUtils.getMyConnection();
            String SQL = "DELETE FROM PHIEUNHAP "
                    + "WHERE MAPN = ? ";
            PreparedStatement ps = conn.prepareStatement(SQL);
            ps.setInt(1, maPN);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Xóa thành công !!!");
            this.dispose();
            QuanLyPhieuNhap.main(null);
        } catch (SQLException ex) {
            System.out.println(ex);
            System.out.println("Xảy ra lỗi!");
        } catch (ClassNotFoundException cx) {

        }
    }//GEN-LAST:event_huyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoPhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bang1;
    private javax.swing.JTable bang2;
    private javax.swing.JTable bang3;
    private javax.swing.JButton chonLai;
    private javax.swing.JTextField donGiaNhap;
    private javax.swing.JButton huy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JFormattedTextField maDoiTac;
    private javax.swing.JLabel maPhieuNhap;
    private javax.swing.JTextField soLuong;
    private javax.swing.JButton taophieunhap;
    private javax.swing.JButton themVaoPhieuNhap;
    private javax.swing.JLabel tongCong;
    // End of variables declaration//GEN-END:variables
}
